# Generated by Django 6.0.2 on 2026-02-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_academicterm_course_programme_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courseoffering',
            name='core_course_level_473213_idx',
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'level', 'term')},
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['level', 'term'], name='core_course_level_edaca1_idx'),
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='academic_year',
        ),
    ]
