# Generated by Django 6.0.2 on 2026-02-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_courseoffering_core_course_level_473213_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='enrolled_students', through='core.Enrollment', to='core.courseoffering'),
        ),
    ]
