# Generated by Django 6.0.2 on 2026-02-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_submission_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submission',
            name='core_submis_assignm_ac9603_idx',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='allow_late_submissions',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='max_submission_attempts',
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='attempt_number',
        ),
    ]
