# Generated by Django 6.0.2 on 2026-02-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_submission_core_submis_assignm_ac9603_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum number of submission attempts allowed'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student', 'attempt_number')},
        ),
    ]
