# Generated by Django 6.0.2 on 2026-02-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_choice_quiz_question_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
