# Generated by Django 6.0.2 on 2026-02-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_text_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
