# Generated by Django 6.0.2 on 2026-02-20 09:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_choice_text_choice_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment for the assignment', null=True, upload_to=core.models.assignment_attachment_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, help_text='File submission if applicable', null=True, upload_to=core.models.submission_file_path),
        ),
    ]
