# Generated by Django 6.0.2 on 2026-02-25 16:34

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_options_user_core_user_email_38052c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='weeks',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('pptx', 'PPTX'), ('pdf', 'PDF'), ('video', 'Video'), ('document', 'Document'), ('link', 'Link')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.course_resource_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.courseoffering')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('topics', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in-progress', 'In Progress'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline', to='core.courseoffering')),
            ],
            options={
                'ordering': ['week'],
                'unique_together': {('course_offering', 'week')},
            },
        ),
    ]
