# Generated by Django 6.0.2 on 2026-03-06 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_courseoffering_weeks_courseresource_courseoutline'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments_weight', models.PositiveIntegerField(default=50, help_text='Percentage weight for assignments (0-100)')),
                ('quizzes_weight', models.PositiveIntegerField(default=50, help_text='Percentage weight for quizzes (0-100)')),
                ('course_offering', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_weight', to='core.courseoffering')),
            ],
            options={
                'verbose_name': 'Grade Weight',
                'verbose_name_plural': 'Grade Weights',
            },
        ),
    ]
