# Generated by Django 6.0.2 on 2026-03-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_gradeweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='reveal_grade',
            field=models.BooleanField(default=False, help_text='If true, student can see their grade after submission'),
        ),
    ]
