# Generated by Django 6.0.2 on 2026-03-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_quiz_reveal_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='room',
            field=models.CharField(default='', max_length=20),
        ),
    ]
