# Generated by Django 6.0.2 on 2026-03-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_courseoffering_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOfferingTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
                ('schedule', models.CharField(max_length=100)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_slots', to='core.courseoffering')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_slots', to='core.teacher')),
            ],
            options={
                'ordering': ['course_offering', 'section__name'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='teaching_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core.courseofferingteacher'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')])),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.programme')),
            ],
            options={
                'ordering': ['level', 'name'],
                'unique_together': {('name', 'level', 'programme')},
            },
        ),
        migrations.AddField(
            model_name='courseofferingteacher',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_slots', to='core.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.section'),
        ),
        migrations.AlterUniqueTogether(
            name='courseofferingteacher',
            unique_together={('course_offering', 'section')},
        ),
    ]
