# Generated by Django 6.0.2 on 2026-03-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_courseofferingteacher_enrollment_teaching_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('teaching_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.courseofferingteacher')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
