# Generated by Django 6.0.2 on 2026-03-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseofferingteacher',
            name='schedule',
        ),
    ]
